In [28]:
import numpy as np
import nnfs 
from nnfs.datasets import spiral_data
nnfs.init()

In [18]:
inputs = [[0,2,4,1], [0.3,-1,-0.6,3], [0.2,-2,0,1]] #3 batches of data
weights1 = [[0.2,0.8,-0.5,1], [0.5,-0.91,0.26,-0.5], [-0.26,-0.27,0.17,0.87], [2,-3,1,0.8]] #4 neurons
np.shape(np.array(weights1).T)

(4, 4)

In [19]:
np.shape(inputs)

(3, 4)

In [20]:
biases1 = [2,3,0.5,1] 
weights2 = [[0.1,-0.14,0.5,1], [-0.5,0.12,-0.33,2], [-0.44,0.73,-0.13,-3]] #3 neurons expecting (4) inputs
biases2 = [-1,2,-0.5] 

layer1_outputs = np.dot(inputs,np.array(weights1).T) + biases1
layer2_outputs = np.dot(layer1_outputs,np.array(weights2).T) + biases2 #the output of the pervious layer will be the input of the next layer


In [ ]:
weights3= [[0.3,0.2,-0.5], [0.1,-0.4,0.6]] #2 neurons expecting (3) inputs
biases3= [2,-1]  

layer3_outputs = np.dot(layer2_outputs,np.array(weights3).T) + biases3

In [23]:
weights4 = [[0.2,0.8], [-0.5,1.0]] #2 neurons expecting (2) inputs
biases4 = [1,-1]    
layer4_outputs = np.dot(layer3_outputs,np.array(weights4).T) + biases4

* The number of inputs of a single neuron will depend on the number of the previous layer's neurons  
* The biases will be one for each neourn on the layer 


In [29]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons) #dot product of inputs X weights (the shape is specified so I don't have to transpose the weights)
        self.biases = np.zeros((1, n_neurons))
    
    def forward(self, inputs):
        # Calculate output values from inputs, weights and biases (Prediction)
        self.output = np.dot(inputs, self.weights) + self.biases

In [31]:
#Dataset
X, y = spiral_data(samples=100, classes=3)
dense1= Layer_Dense(2,3)
dense1.forward(X)
print(dense1.output[:5]) #print the first 5 

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.61496298e-05 -5.70940247e-05 -1.16960771e-04]
 [-7.69893813e-05 -4.75328154e-04 -2.12466970e-04]
 [-1.19454686e-04 -6.26299181e-04 -3.77396704e-04]
 [-1.59333722e-04 -8.86327529e-04 -4.81519091e-04]]
